apiVersion: v1
kind: Service
metadata:
  name: <%= appName %>-service
spec:
  type: NodePort
  selector:
    app: <%= appName %>
  ports:
    - protocol: TCP
      port: 80
      targetPort: <%= appPort %>
      nodePort: <%= exposedPort %>  # Manually specified NodePort
