apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= appName %>-deployment
spec:
  replicas: <%= replicas %>
  selector:
    matchLabels:
      app: <%= appName %>
  template:
    metadata:
      labels:
        app: <%= appName %>
    spec:
      containers:
        - name: <%= appName %>
          image: <%= appImageUrlWithTag %>
          imagePullPolicy: Always
          ports:
            - containerPort: <%= appInternalPort %>

